site_name: Touristeer

repo_name: Github Touristeer 
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T01-Touristeer-


nav:
  - Início: index.md
  - Visão de Produto e Projeto: 
    - Cenário Atual do Cliente e Negócio: sections/docPage/1-cenarioAtual.md
    - Solução Proposta: sections/docPage/2-solucaoProp.md
    - Estratégias de Engenharia de Software: sections/docPage/3-estrategias.md
    - Engenharia de Requisitos: sections/docPage/10-engenhariaRequisitos.md
    - Cronograma e Entregas: sections/docPage/4-cronograma.md
    - Interação entre Equipe e Cliente: sections/docPage/5-interacaoEqCliente.md
    - Requisitos: sections/docPage/7-requisitos.md
    - DOR e DOD: sections/docPage/8-dor-e-dod.md
    - Backlog do Produto: sections/docPage/9-backlog.md
    - Protótipos: sections/docPage/11-prototipos.md
    - Lições Aprendidas: sections/docPage/6-licoesAprendidas.md
    - Estudos de Casos: 
      - PBB: sections/docPage/PBB.md
      - USM: sections/docPage/USM.md
      - UC: sections/docPage/UC.md
  - Entregas:
    - Unidade 1: sections/entregas/unidade1.md
    - Unidade 2: sections/entregas/unidade2.md 
    - Unidade 3: sections/entregas/unidade3.md
    - Unidade 4: sections/entregas/unidade4.md

theme: 
  name: material
  language: pt-BR

  features:
    - content.code.annotate
      - content.tabs.link
      - header.autohide
      - navigation.instant
      - navigation.top
      - navigation.tracking
      
  
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: '2c3094'
    accent: '2c3094'
    toggle:
      icon: material/weather-night
      name: Tema claro

  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: '2c3094'
    accent: '2c3094'
    toggle:
      icon: material/weather-sunny
      name: Tema escuro

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
